{{- if $.Values.global.render -}}
{{- if $.Values.global.namespace.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $.Values.networkpolicy.name }}
  namespace: {{ $.Values.networkpolicy.namespace }}
spec:
  podSelector:
  ingress: []
{{- end -}}
{{- end -}}  
