{{- if $.Values.global.render -}}
{{- if $.Values.global.namespace.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ $.Values.resourcequota.objects.name }}
  namespace: {{ $.Values.resourcequota.objects.namespace }}
spec:
  hard:
    pods: {{ $.Values.resourcequota.objects.spec.pods }} 
    configmaps: {{ $.Values.resourcequota.objects.spec.configmaps }}  
    persistentvolumeclaims: {{ $.Values.resourcequota.objects.spec.persistentvolumeclaims }}  
    replicationcontrollers: {{ $.Values.resourcequota.objects.spec.replicationcontrollers }}  
    secrets: {{ $.Values.resourcequota.objects.spec.secrets }} 
    services: {{ $.Values.resourcequota.objects.spec.services }} 
{{- end -}}
{{- end -}}     