{{- if $.Values.global.render -}}
{{- if $.Values.global.namespace.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Values.role.name }}
  namespace: {{ $.Values.role.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.role.roleref.name }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ $.Values.role.subjects.name }}
{{- end -}}
{{- end -}}  
